#################################################
# xl apply -f app.yaml --values version=34
#################################################
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/giss
  type: udm.Application
- name: !format Applications/giss/1.0.%version%
  type: udm.DeploymentPackage
  deployables:
  - name: changesets
    type: liquibase.Changelog
    changeLogFile: root.xml
    rollbackVersion: !value version
    file: !file "changesets"
